export const LAST_THREE_MONTH_DASHBOARD_DETAILS_REQUEST =
  "LAST_THREE_MONTH_DASHBOARD_DETAILS_REQUEST";
export const LAST_THREE_MONTH_DASHBOARD_DETAILS_SUCCESS =
  "LAST_THREE_MONTH_DASHBOARD_DETAILS_SUCCESS";
export const LAST_THREE_MONTH_DASHBOARD_DETAILS_FAILURE =
  "LAST_THREE_MONTH_DASHBOARD_DETAILS_FAILURE";

export const SALARY_CURRENT_MONTH_GET_REQUEST =
  "SALARY_CURRENT_MONTH_GET_REQUEST";
export const SALARY_CURRENT_MONTH_GET_SUCCESS =
  "SALARY_CURRENT_MONTH_GET_SUCCESS";
export const SALARY_CURRENT_MONTH_GET_FAILURE =
  "SALARY_CURRENT_MONTH_GET_FAILURE";

export const EXTRAINCOME_CURRENT_MONTH_GET_REQUEST =
  "EXTRAINCOME_CURRENT_MONTH_GET_REQUEST";
export const EXTRAINCOME_CURRENT_MONTH_GET_SUCCESS =
  "EXTRAINCOME_CURRENT_MONTH_GET_SUCCESS";
export const EXTRAINCOME_CURRENT_MONTH_GET_FAILURE =
  "EXTRAINCOME_CURRENT_MONTH_GET_FAILURE";

export const EXPENSE_CURRENT_MONTH_GET_REQUEST =
  "EXPENSE_CURRENT_MONTH_GET_REQUEST";
export const EXPENSE_CURRENT_MONTH_GET_SUCCESS =
  "EXPENSE_CURRENT_MONTH_GET_SUCCESS";
export const EXPENSE_CURRENT_MONTH_GET_FAILURE =
  "EXPENSE_CURRENT_MONTH_GET_FAILURE";
