export const EXPENSE_DETAIL_CREATE_REQUEST = "EXPENSE_DETAIL_CREATE_REQUEST";
export const EXPENSE_DETAIL_CREATE_SUCCESS = "EXPENSE_DETAIL_CREATE_SUCCESS";
export const EXPENSE_DETAIL_CREATE_FAILURE = "EXPENSE_DETAIL_CREATE_FAILURE";

export const EXPENSE_DETAIL_IMPORT_REQUEST = "EXPENSE_DETAIL_IMPORT_REQUEST";
export const EXPENSE_DETAIL_IMPORT_SUCCESS = "EXPENSE_DETAIL_IMPORT_SUCCESS";
export const EXPENSE_DETAIL_IMPORT_FAILURE = "EXPENSE_DETAIL_IMPORT_FAILURE";

export const EXPENSE_DETAIL_LIST_REQUEST = "EXPENSE_DETAIL_LIST_REQUEST";
export const EXPENSE_DETAIL_LIST_SUCCESS = "EXPENSE_DETAIL_LIST_SUCCESS";
export const EXPENSE_DETAIL_LIST_FAILURE = "EXPENSE_DETAIL_LIST_FAILURE";

export const EXPENSE_DETAIL_BY_ID_REQUEST = "EXPENSE_DETAIL_BY_ID_REQUEST";
export const EXPENSE_DETAIL_BY_ID_SUCCESS = "EXPENSE_DETAIL_BY_ID_SUCCESS";
export const EXPENSE_DETAIL_BY_ID_FAILURE = "EXPENSE_DETAIL_BY_ID_FAILURE";

export const EXPENSE_DETAIL_UPDATE_REQUEST = "EXPENSE_DETAIL_UPDATE_REQUEST";
export const EXPENSE_DETAIL_UPDATE_SUCCESS = "EXPENSE_DETAIL_UPDATE_SUCCESS";
export const EXPENSE_DETAIL_UPDATE_FAILURE = "EXPENSE_DETAIL_UPDATE_FAILURE";

export const EXPENSE_DETAIL_DELETE_REQUEST = "EXPENSE_DETAIL_DELETE_REQUEST";
export const EXPENSE_DETAIL_DELETE_SUCCESS = "EXPENSE_DETAIL_DELETE_SUCCESS";
export const EXPENSE_DETAIL_DELETE_FAILURE = "EXPENSE_DETAIL_DELETE_FAILURE";
