export const EXTRAINCOME_DETAIL_CREATE_REQUEST =
  "EXTRAINCOME_DETAIL_CREATE_REQUEST";
export const EXTRAINCOME_DETAIL_CREATE_SUCCESS =
  "EXTRAINCOME_DETAIL_CREATE_SUCCESS";
export const EXTRAINCOME_DETAIL_CREATE_FAILURE =
  "EXTRAINCOME_DETAIL_CREATE_FAILURE";

export const EXTRAINCOME_DETAIL_LIST_REQUEST =
  "EXTRAINCOME_DETAIL_LIST_REQUEST";
export const EXTRAINCOME_DETAIL_LIST_SUCCESS =
  "EXTRAINCOME_DETAIL_LIST_SUCCESS";
export const EXTRAINCOME_DETAIL_LIST_FAILURE =
  "EXTRAINCOME_DETAIL_LIST_FAILURE";

export const EXTRAINCOME_DETAIL_BY_ID_REQUEST =
  "EXTRAINCOME_DETAIL_BY_ID_REQUEST";
export const EXTRAINCOME_DETAIL_BY_ID_SUCCESS =
  "EXTRAINCOME_DETAIL_BY_ID_SUCCESS";
export const EXTRAINCOME_DETAIL_BY_ID_FAILURE =
  "EXTRAINCOME_DETAIL_BY_ID_FAILURE";

export const EXTRAINCOME_DETAIL_UPDATE_REQUEST =
  "EXTRAINCOME_DETAIL_UPDATE_REQUEST";
export const EXTRAINCOME_DETAIL_UPDATE_SUCCESS =
  "EXTRAINCOME_DETAIL_UPDATE_SUCCESS";
export const EXTRAINCOME_DETAIL_UPDATE_FAILURE =
  "EXTRAINCOME_DETAIL_UPDATE_FAILURE";

export const EXTRAINCOME_DETAIL_DELETE_REQUEST =
  "EXTRAINCOME_DETAIL_DELETE_REQUEST";
export const EXTRAINCOME_DETAIL_DELETE_SUCCESS =
  "EXTRAINCOME_DETAIL_DELETE_SUCCESS";
export const EXTRAINCOME_DETAIL_DELETE_FAILURE =
  "EXTRAINCOME_DETAIL_DELETE_FAILURE";
