export const GROCERY_DETAIL_CREATE_REQUEST = "GROCERY_DETAIL_CREATE_REQUEST";
export const GROCERY_DETAIL_CREATE_SUCCESS = "GROCERY_DETAIL_CREATE_SUCCESS";
export const GROCERY_DETAIL_CREATE_FAILURE = "GROCERY_DETAIL_CREATE_FAILURE";

export const GROCERY_DETAIL_IMPORT_REQUEST = "GROCERY_DETAIL_IMPORT_REQUEST";
export const GROCERY_DETAIL_IMPORT_SUCCESS = "GROCERY_DETAIL_IMPORT_SUCCESS";
export const GROCERY_DETAIL_IMPORT_FAILURE = "GROCERY_DETAIL_IMPORT_FAILURE";

export const GROCERY_DETAIL_LIST_REQUEST = "GROCERY_DETAIL_LIST_REQUEST";
export const GROCERY_DETAIL_LIST_SUCCESS = "GROCERY_DETAIL_LIST_SUCCESS";
export const GROCERY_DETAIL_LIST_FAILURE = "GROCERY_DETAIL_LIST_FAILURE";

export const GROCERY_DETAIL_BY_ID_REQUEST = "GROCERY_DETAIL_BY_ID_REQUEST";
export const GROCERY_DETAIL_BY_ID_SUCCESS = "GROCERY_DETAIL_BY_ID_SUCCESS";
export const GROCERY_DETAIL_BY_ID_FAILURE = "GROCERY_DETAIL_BY_ID_FAILURE";

export const GROCERY_DETAIL_UPDATE_REQUEST = "GROCERY_DETAIL_UPDATE_REQUEST";
export const GROCERY_DETAIL_UPDATE_SUCCESS = "GROCERY_DETAIL_UPDATE_SUCCESS";
export const GROCERY_DETAIL_UPDATE_FAILURE = "GROCERY_DETAIL_UPDATE_FAILURE";

export const GROCERY_DETAIL_DELETE_REQUEST = "GROCERY_DETAIL_DELETE_REQUEST";
export const GROCERY_DETAIL_DELETE_SUCCESS = "GROCERY_DETAIL_DELETE_SUCCESS";
export const GROCERY_DETAIL_DELETE_FAILURE = "GROCERY_DETAIL_DELETE_FAILURE";
