export const SALARY_DETAIL_CREATE_REQUEST = "SALARY_DETAIL_CREATE_REQUEST";
export const SALARY_DETAIL_CREATE_SUCCESS = "SALARY_DETAIL_CREATE_SUCCESS";
export const SALARY_DETAIL_CREATE_FAILURE = "SALARY_DETAIL_CREATE_FAILURE";

export const SALARY_DETAIL_LIST_REQUEST = "SALARY_DETAIL_LIST_REQUEST";
export const SALARY_DETAIL_LIST_SUCCESS = "SALARY_DETAIL_LIST_SUCCESS";
export const SALARY_DETAIL_LIST_FAILURE = "SALARY_DETAIL_LIST_FAILURE";

export const SALARY_DETAIL_BY_ID_REQUEST = "SALARY_DETAIL_BY_ID_REQUEST";
export const SALARY_DETAIL_BY_ID_SUCCESS = "SALARY_DETAIL_BY_ID_SUCCESS";
export const SALARY_DETAIL_BY_ID_FAILURE = "SALARY_DETAIL_BY_ID_FAILURE";

export const SALARY_DETAIL_UPDATE_REQUEST = "SALARY_DETAIL_UPDATE_REQUEST";
export const SALARY_DETAIL_UPDATE_SUCCESS = "SALARY_DETAIL_UPDATE_SUCCESS";
export const SALARY_DETAIL_UPDATE_FAILURE = "SALARY_DETAIL_UPDATE_FAILURE";

export const SALARY_DETAIL_DELETE_REQUEST = "SALARY_DETAIL_DELETE_REQUEST";
export const SALARY_DETAIL_DELETE_SUCCESS = "SALARY_DETAIL_DELETE_SUCCESS";
export const SALARY_DETAIL_DELETE_FAILURE = "SALARY_DETAIL_DELETE_FAILURE";

export const SALARY_REPORT_CREATE_REQUEST = "SALARY_REPORT_CREATE_REQUEST";
export const SALARY_REPORT_CREATE_SUCCESS = "SALARY_REPORT_CREATE_SUCCESS";
export const SALARY_REPORT_CREATE_FAILURE = "SALARY_REPORT_CREATE_FAILURE";
