export const USER_REGISTRAION_REQUEST = "USER_REGISTRAION_REQUEST";
export const USER_REGISTRAION_SUCCESS = "USER_REGISTRAION_SUCCESS";
export const USER_REGISTRAION_FAILURE = "USER_REGISTRAION_FAILURE";

export const USER_EMAIL_ACTIVATE_REQUEST = "USER_EMAIL_ACTIVATE_REQUEST";
export const USER_EMAIL_ACTIVATE_SUCCESS = "USER_EMAIL_ACTIVATE_SUCCESS";
export const USER_EMAIL_ACTIVATE_FAILURE = "USER_EMAIL_ACTIVATE_FAILURE";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_FORGOTPASSWORD_REQUEST = "USER_FORGOTPASSWORD_REQUEST";
export const USER_FORGOTPASSWORD_SUCCESS = "USER_FORGOTPASSWORD_SUCCESS";
export const USER_FORGOTPASSWORD_FAILURE = "USER_FORGOTPASSWORD_FAILURE";

export const USER_ACCOUNTACTIVATION_REQUEST = "USER_ACCOUNTACTIVATION_REQUEST";
export const USER_ACCOUNTACTIVATION_SUCCESS = "USER_ACCOUNTACTIVATION_SUCCESS";
export const USER_ACCOUNTACTIVATION_FAILURE = "USER_ACCOUNTACTIVATION_FAILURE";

export const USER_PASSWORDRESET_REQUEST = "USER_PASSWORDRESET_REQUEST";
export const USER_PASSWORDRESET_SUCCESS = "USER_PASSWORDRESET_SUCCESS";
export const USER_PASSWORDRESET_FAILURE = "USER_PASSWORDRESET_FAILURE";

export const USER_EMAILRESET_REQUEST = "USER_EMAILRESET_REQUEST";
export const USER_EMAILRESET_SUCCESS = "USER_EMAILRESET_SUCCESS";
export const USER_EMAILRESET_FAILURE = "USER_EMAILRESET_FAILURE";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAILURE = "USER_LIST_FAILURE";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAILURE = "USER_UPDATE_FAILURE";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAILURE = "USER_DELETE_FAILURE";
